theme: jekyll-theme-minimal
title: Power-rangers Datastory
description: A datastory website for power-rangers group ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
